export default{
    name:'product',
    title:'Product',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string',
        },
        {
            name: 'isActive',
            title:'isActive',
            type: 'string',
          },
        {
            name:'description',
            title:'Description',
            type:'text',
        },
        {
            name:'storeid',
            title:'Store ID',
            type:'text',
        },
        {
            name:'slogan',
            title:'Slogan',
            type:'text'
        },
        {
            name:'category',
            title:'Category',
            type:'text'
        },
        {
            name:'subCategory',
            title:'Sub Category'
            ,type:'text'
        },
        {
            name:'price',
            title:'Price',
            type:'number',
        },
        {
            name:'discount',
            title:'Discount',
            type:'number',
        },
        {
            name:'quantity',
            title:'Quantity',
            type:'number'
        }
        ,
        {
            name:'image',
            title:'image',
            type:'array',
            of:[{type:'image'}]
        }
    ]
}